In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg

#### 6. 1. Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

In [2]:
# Проверка решения 
A = np.array([[1, 1,-1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
B = np.array([[0, -2, 4]])

print(f'Запишем расширенную матрицу системы:')
C = np.concatenate((A,B.T), axis=1)
print (C)
print(f'Ранг матрицы r1={np.linalg.matrix_rank(A, 0.0001)}')
print(f'Ранг расширенной матрицы r2={np.linalg.matrix_rank(C, 0.0001)}')

Запишем расширенную матрицу системы:
[[ 1  1 -1 -2  0]
 [ 2  1 -1  1 -2]
 [ 1  1 -3  1  4]]
Ранг матрицы r1=3
Ранг расширенной матрицы r2=3


$$rank A=rank \tilde A.$$

Значит, система совместна и имеет бесконечное множество решений.

Общим решением будет:

$x_1=-6\cdot C-2$

$x_2=13\cdot C$

$x_3=3\cdot C-2$

$x_4=2\cdot C$

#### 6. 2.a Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

In [3]:
# Проверка решения 
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
B = np.array([[4, -17, 0]])

print(f'Запишем расширенную матрицу системы:')
C = np.concatenate((A,B.T), axis=1)
print (C)
print(f'Ранг матрицы r1={np.linalg.matrix_rank(A, 0.0001)}')
print(f'Ранг расширенной матрицы r2={np.linalg.matrix_rank(C, 0.0001)}')

Запишем расширенную матрицу системы:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Ранг матрицы r1=3
Ранг расширенной матрицы r2=3


$$rank A=rank \tilde A.$$

Значит, система совместна и имеет единственное решение.


#### 6.2.б Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

In [4]:
# Проверка решения 
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
B = np.array([[1, -2, 5]])

print(f'Запишем расширенную матрицу системы:')
C = np.concatenate((A,B.T), axis=1)
print (C)
print(f'Ранг матрицы r1={np.linalg.matrix_rank(A, 0.0001)}')
print(f'Ранг расширенной матрицы r2={np.linalg.matrix_rank(C, 0.0001)}')

Запишем расширенную матрицу системы:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Ранг матрицы r1=1
Ранг расширенной матрицы r2=2


$$rank A<rank \tilde A.$$

Значит, система несовместна и не имеет решений.


#### 6.2.в Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


In [5]:
# Проверка решения 
A = np.array([[1, 2, 5], [3, 1, -8]])
B = np.array([[4, -2]])

print(f'Запишем расширенную матрицу системы:')
C = np.concatenate((A,B.T), axis=1)
print (C)
print(f'Ранг матрицы r1={np.linalg.matrix_rank(A, 0.0001)}')
print(f'Ранг расширенной матрицы r2={np.linalg.matrix_rank(C, 0.0001)}')

Запишем расширенную матрицу системы:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг матрицы r1=2
Ранг расширенной матрицы r2=2


$$rank A=rank \tilde A<n=3$$

Значит, система совместна и имеет бесконечное количество решений.

#### 6.3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [6]:
# Проверка решения 
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
B = np.array([[3, 2, 4, 1]])

print(f'Запишем расширенную матрицу системы:')
C = np.concatenate((A,B.T), axis=1)
print (C)
print(f'Ранг матрицы r1={np.linalg.matrix_rank(A, 0.0001)}')
print(f'Ранг расширенной матрицы r2={np.linalg.matrix_rank(C, 0.0001)}')

Запишем расширенную матрицу системы:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Ранг матрицы r1=4
Ранг расширенной матрицы r2=4


$$rank A=rank \tilde A.$$

Значит, система совместна и имеет единственное решение.

####  7.2*. Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

In [7]:
A = np.array([ [1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = scipy.linalg.lu(A)
print(f'L-матрица:')
print(L)

# проверка
print(f'Матрица LU\n{np.dot(L, U)}')

L-матрица:
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]
Матрица LU
[[ 3. 26. 30.]
 [ 2.  9. 12.]
 [ 1.  2.  4.]]


In [8]:
# проверка решения с "листочка"
A = np.array([ [1, 0, 0], [2, 1, 0], [3, 4, 1]])
B = np.array([ [1, 2, 4], [0, 5, 4], [0, 0, 2]])
print(f'Матрица LU\n{np.dot(A, B)}')

Матрица LU
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]


####  7.2*.б Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [9]:
A = np.array([ [1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
P, L, U = scipy.linalg.lu(A)
print(f'L-матрица:')
print(L)

# проверка
print(f'Матрица LU\n{np.dot(L, U)}')

L-матрица:
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75       -0.25        1.          0.        ]
 [ 0.25        0.75       -0.17073171  1.        ]]
Матрица LU
[[ 4. 22. 53. 33.]
 [ 2.  5.  8.  9.]
 [ 3. 18. 29. 18.]
 [ 1.  1.  2.  4.]]


In [10]:
# проверка решения "на листочке"
A = np.array([ [1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
B = np.array([ [1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])
print(f'Матрица LU\n{np.dot(A, B)}')

Матрица LU
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]


####  7.3*. Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [18]:
A = np.array([ [2, 1, 3], [11, 7, 5], [9, 8, 4]])
P, L, U = scipy.linalg.lu(A)

# вектор правых частей
B = np.array([1, -6, -5])
X = np.linalg.solve(A, B)
print(f'Решение системы: {X}')

Решение системы: [-1.  0.  1.]


In [23]:
# проверка нахождения L и U "на листочке"
L = np.array([ [1, 0, 0], [11/2, 1, 0], [9/2, 7/3, 1]])
U = np.array([ [2, 1, 3], [0, 3/2, -23/2], [0, 0, 52/3]])
print(f'Матрица LU\n{np.dot(L, U)}')

# Решим уравнение L*y=b
B = np.array([[1], [-6], [-5]])
y = np.dot(np.linalg.inv(L),B)
print(f'Матрица Y\n{y}')

# Решим уравнение U*x=y
x = np.dot(np.linalg.inv(U),y)
print(f'Решение системы:\n {x}')

Матрица LU
[[ 2.  1.  3.]
 [11.  7.  5.]
 [ 9.  8.  4.]]
Матрица Y
[[  1.        ]
 [-11.5       ]
 [ 17.33333333]]
Решение системы:
 [[-1.0000000e+00]
 [ 8.8817842e-16]
 [ 1.0000000e+00]]


#### 7. 4*.  Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [38]:
from numpy.linalg import cholesky
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])

#найдем матрицу l
L = np.linalg.cholesky(A)
print(f'Матрица L\n {L}')

#найдем матрицу L.T
L_t = L.transpose()
print(f'Матрица LT\n {L_t}')

# Решим уравнение L*y=b
B = np.array([[531], [-460], [193]])
y = np.dot(np.linalg.inv(L),B)
print(f'Матрица Y\n{y}')

# Решим уравнение L_t*x=y
x = np.dot(np.linalg.inv(L_t),y)
print(f'Решение системы:\n {x}')

Матрица L
 [[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]
Матрица LT
 [[ 9. -5.  5.]
 [ 0.  5.  2.]
 [ 0.  0.  3.]]
Матрица Y
[[ 59.]
 [-33.]
 [-12.]]
Решение системы:
 [[ 6.]
 [-5.]
 [-4.]]
